window.CP_CASE.model = [
  ['0:00','Doctor','David, I am one of the doctors. I can see you look uncomfortable. I will ask focused questions, but chest tightness like this can be serious, so I may need to organise urgent help while we talk.'],
  ['0:24','David','Doctor, I think it is just indigestion, but my chest feels really tight.'],
  ['0:34','Doctor','I understand why you thought of indigestion. When did this start, and what were you doing?'],
  ['0:48','David','About 45 minutes ago. I was carrying boxes at work.'],
  ['0:58','Doctor','Where is the discomfort, what does it feel like, and how severe is it?'],
  ['1:13','David','It is in the middle of my chest. It feels heavy and tight, about eight out of ten.'],
  ['1:26','Doctor','Does it travel to your arm, jaw, back or neck?'],
  ['1:37','David','Yes, to my left arm and jaw.'],
  ['1:46','Doctor','Have you felt sweaty, sick, short of breath, faint, or had vomiting?'],
  ['1:58','David','I am sweaty, nauseated and short of breath. I have not fainted.'],
  ['2:05','Doctor','David, I am concerned this could be coming from your heart. I am arranging an ambulance now while I continue checking you.'],
  ['2:23','David','An ambulance? I thought it was indigestion.'],
  ['2:33','Doctor','Indigestion is possible, but heavy central pressure with radiation, sweating, nausea and breathlessness is not safe to manage as indigestion here.'],
  ['2:56','Doctor','Please call an ambulance for ongoing high-risk chest pain. David, stay resting here while I ask a few more focused questions.'],
  ['3:15','Doctor','Do you smoke, or have high blood pressure, cholesterol, diabetes, or a family history of early heart disease?'],
  ['3:32','David','I smoke, have high blood pressure and cholesterol, and my father had a heart attack in his fifties.'],
  ['3:48','Doctor','What medicines do you take, and do you have an aspirin allergy, bleeding problem, or blood thinner?'],
  ['4:03','David','I take blood-pressure and cholesterol tablets. No aspirin allergy, bleeding problem or blood thinner.'],
  ['4:19','Examiner','David looks pale and sweaty. Pulse 104, blood pressure 155 over 92, respiratory rate 22, oxygen saturation 95 percent on room air, temperature 36.8. Heart sounds are normal and chest is clear.'],
  ['4:47','Doctor','Thank you. I would keep him resting, obtain an ECG if immediately available without delaying transfer, and consider aspirin 300 milligrams if no contraindication. Routine oxygen is not indicated at 95 percent.'],
  ['5:18','David','Can I just drive myself? I have an important meeting.'],
  ['5:28','Doctor','I understand the meeting matters, but I do not want you driving. Your condition could change suddenly, and the ambulance can monitor and treat you on the way.'],
  ['5:52','David','Can we wait for the ECG or blood test first?'],
  ['6:01','Doctor','No. A normal early ECG or improvement does not safely exclude a heart problem, and clinic blood tests would delay the care you need.'],
  ['6:25','David','Are you saying I am having a heart attack?'],
  ['6:34','Doctor','I cannot confirm the exact cause here, but the pattern is concerning enough that the safest action is urgent monitored transfer.'],
  ['6:55','Doctor','Can you tell me what you understand about the plan and why I do not want you to drive?'],
  ['7:08','David','You are worried it could be my heart, so I need an ambulance and should not drive.'],
  ['7:18','Doctor','That is right. I will help contact your wife, keep checking you, and prepare a structured handover for the ambulance team.'],
  ['7:38','Doctor','Handover: David Nguyen, 58, 45 minutes of exertional heavy central chest pressure radiating to the left arm and jaw, with sweating, nausea and breathlessness; cardiovascular risk factors; pale and tachycardic; urgent assessment for high-risk cardiac chest pain.'],
  ['8:00','End','Station endpoint.']
];
window.CP_CASE.decisions = [
  {title:'Do not accept the patient label', cue:'Acknowledge “indigestion” without treating it as the diagnosis.', question:'What danger has not been excluded?'},
  {title:'Act before proof', cue:'The high-risk pattern crosses the action threshold by about two minutes.', question:'Is there enough danger to act now while assessment continues?'},
  {title:'No private driving', cue:'Hospital advice is incomplete unless transport safety is explicit.', question:'What could happen during private transport?'},
  {title:'No clinic-test delay', cue:'One early test cannot cancel the clinical pattern.', question:'Would this test safely change the transfer decision here?'},
  {title:'Recover explicitly', cue:'If you started with reflux, say what changed and redirect.', question:'What new information makes the first idea unsafe?'}
];
